import matplotlib
matplotlib.use('Agg')

from matplotlib import pyplot as plt
import numpy as np


xdata=[];ydata=[];
f=open('gmt_mock.norm.dat','r')
rawdata=f.readlines()[2:]
for i in rawdata:
    i=i.strip()
    x=float(i.split()[0])
    y=float(i.split()[1])
#    print(x,y)
    xdata.append(x)
    ydata.append(y)
f.close()

print('')
f=open('radius.dat','r')
radius=f.read()
print('radius:',radius)
f.close()
f=open('config.dat','r')
rawdata=f.readlines()
noa=len(rawdata)
ni=rawdata[0].split()[-1]
nr=rawdata[0].split()[-2]

print('noa:',noa)
print('nr:',nr)
print('ni:',ni)
f.close()

ypeak=round(ydata[np.argsort(ydata)[-1]],4)
xpeak=round(xdata[np.argsort(ydata)[-1]],2)
print('peak at (xpeak,ypeak)=',xpeak,',',ypeak)

plt.plot(xdata,ydata,'o-')
plt.plot( [xpeak,xpeak],[ypeak,0])
plt.scatter(xpeak,ypeak,c='r',s=50,label= \
            'sphere no:' + str(noa) + '; radius:'+str(radius)+'nm')    
plt.scatter(xpeak,ypeak,c='r',s=50,label='Re(RI)='+str(nr)+ \
            ' , Im(RI)=' + str(ni))
plt.scatter(xpeak,ypeak,c='r',s=50,label='peak at (x,y)= ('+str(xpeak)+ \
            ' , ' + str(ypeak)+')')

title='Mock Cext vs. wavelength (nm) generated by GMT'
plt.title(title)
plt.legend(loc ="lower left")



plt.savefig('gmt_mock.norm.pdf')
plt.savefig('gmt_mock.norm.png')
